//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Traductor.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Diccionario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diccionario() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Traductor.Recursos.Diccionario", typeof(Diccionario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -&gt; Tipo de figura inexistente.
        /// </summary>
        internal static string ___Tipo_de_figura_inexistente {
            get {
                return ResourceManager.GetString("-> Tipo de figura inexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupado.
        /// </summary>
        internal static string Agrupado {
            get {
                return ResourceManager.GetString("Agrupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura.
        /// </summary>
        internal static string Altura {
            get {
                return ResourceManager.GetString("Altura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        internal static string Área {
            get {
                return ResourceManager.GetString("Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base Superior.
        /// </summary>
        internal static string Base_Superior {
            get {
                return ResourceManager.GetString("Base Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Círculo.
        /// </summary>
        internal static string Circulo {
            get {
                return ResourceManager.GetString("Circulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a círculos, la sumatoria de sus áreas y perímetros es la siguiente: Área.
        /// </summary>
        internal static string círculos__la_sumatoria_de_sus_áreas_y_perímetros_es_la_siguiente__Área {
            get {
                return ResourceManager.GetString("círculos, la sumatoria de sus áreas y perímetros es la siguiente: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrado.
        /// </summary>
        internal static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cuadrados, la sumatoria de sus áreas y perímetros es la siguiente: Área.
        /// </summary>
        internal static string cuadrados__la_sumatoria_de_sus_áreas_y_perímetros_es_la_siguiente__Área {
            get {
                return ResourceManager.GetString("cuadrados, la sumatoria de sus áreas y perímetros es la siguiente: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle.
        /// </summary>
        internal static string Detalle {
            get {
                return ResourceManager.GetString("Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Figuras procesadas.
        /// </summary>
        internal static string Figuras_procesadas {
            get {
                return ResourceManager.GetString("Figuras procesadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay solo un círculo, estos son los datos calculados: Área.
        /// </summary>
        internal static string Hay_solo_un_círculo__estos_son_los_datos_calculados__Área {
            get {
                return ResourceManager.GetString("Hay solo un círculo, estos son los datos calculados: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay solo un cuadrado, estos son los datos calculados: Área.
        /// </summary>
        internal static string Hay_solo_un_cuadrado__estos_son_los_datos_calculados__Área {
            get {
                return ResourceManager.GetString("Hay solo un cuadrado, estos son los datos calculados: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay solo un hexágono, estos son los datos calculados: Área.
        /// </summary>
        internal static string Hay_solo_un_hexágono__estos_son_los_datos_calculados__Área {
            get {
                return ResourceManager.GetString("Hay solo un hexágono, estos son los datos calculados: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay solo un pentágono, estos son los datos calculados: Área.
        /// </summary>
        internal static string Hay_solo_un_pentágono__estos_son_los_datos_calculados__Área {
            get {
                return ResourceManager.GetString("Hay solo un pentágono, estos son los datos calculados: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay solo un rectángulo, estos son los datos calculados: Área.
        /// </summary>
        internal static string Hay_solo_un_rectángulo__estos_son_los_datos_calculados__Área {
            get {
                return ResourceManager.GetString("Hay solo un rectángulo, estos son los datos calculados: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay solo un trapecio, estos son los datos calculados: Área.
        /// </summary>
        internal static string Hay_solo_un_trapecio__estos_son_los_datos_calculados__Área {
            get {
                return ResourceManager.GetString("Hay solo un trapecio, estos son los datos calculados: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay solo un triángulo, estos son los datos calculados: Área.
        /// </summary>
        internal static string Hay_solo_un_triángulo__estos_son_los_datos_calculados__Área {
            get {
                return ResourceManager.GetString("Hay solo un triángulo, estos son los datos calculados: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay un total de.
        /// </summary>
        internal static string Hay_un_total_de {
            get {
                return ResourceManager.GetString("Hay un total de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hexágono.
        /// </summary>
        internal static string Hexagono {
            get {
                return ResourceManager.GetString("Hexagono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hexágonos, la sumatoria de sus áreas y perímetros es la siguiente: Área.
        /// </summary>
        internal static string hexágonos__la_sumatoria_de_sus_áreas_y_perímetros_es_la_siguiente__Área {
            get {
                return ResourceManager.GetString("hexágonos, la sumatoria de sus áreas y perímetros es la siguiente: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de formas vacía!.
        /// </summary>
        internal static string Lista_de_formas_vacía_ {
            get {
                return ResourceManager.GetString("Lista de formas vacía!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pentágono.
        /// </summary>
        internal static string Pentagono {
            get {
                return ResourceManager.GetString("Pentagono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pentágonos, la sumatoria de sus áreas y perímetros es la siguiente: Área.
        /// </summary>
        internal static string pentágonos__la_sumatoria_de_sus_áreas_y_perímetros_es_la_siguiente__Área {
            get {
                return ResourceManager.GetString("pentágonos, la sumatoria de sus áreas y perímetros es la siguiente: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perímetro.
        /// </summary>
        internal static string Perímetro {
            get {
                return ResourceManager.GetString("Perímetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Radio.
        /// </summary>
        internal static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectángulo.
        /// </summary>
        internal static string Rectangulo {
            get {
                return ResourceManager.GetString("Rectangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rectángulos, la sumatoria de sus áreas y perímetros es la siguiente: Área.
        /// </summary>
        internal static string rectángulos__la_sumatoria_de_sus_áreas_y_perímetros_es_la_siguiente__Área {
            get {
                return ResourceManager.GetString("rectángulos, la sumatoria de sus áreas y perímetros es la siguiente: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sumatoria de áreas.
        /// </summary>
        internal static string Sumatoria_de_áreas {
            get {
                return ResourceManager.GetString("Sumatoria de áreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sumatoria de perímetros.
        /// </summary>
        internal static string Sumatoria_de_perímetros {
            get {
                return ResourceManager.GetString("Sumatoria de perímetros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL.
        /// </summary>
        internal static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapecio.
        /// </summary>
        internal static string Trapecio {
            get {
                return ResourceManager.GetString("Trapecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a trapecios, la sumatoria de sus áreas y perímetros es la siguiente: Área.
        /// </summary>
        internal static string trapecios__la_sumatoria_de_sus_áreas_y_perímetros_es_la_siguiente__Área {
            get {
                return ResourceManager.GetString("trapecios, la sumatoria de sus áreas y perímetros es la siguiente: Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulo.
        /// </summary>
        internal static string Triangulo {
            get {
                return ResourceManager.GetString("Triangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a triángulos, la sumatoria de sus áreas y perímetros es la siguiente: Área.
        /// </summary>
        internal static string triángulos__la_sumatoria_de_sus_áreas_y_perímetros_es_la_siguiente__Área {
            get {
                return ResourceManager.GetString("triángulos, la sumatoria de sus áreas y perímetros es la siguiente: Área", resourceCulture);
            }
        }
    }
}
